### ISSUE TITLE
Info on usage data monitor

### ISSUE THREAD

**Issue by docop** [dewiweb/spacemouse-osc#4]
Hi
 So i did try over a Debian system your app and while the appimage do open up fine.. i'm not sure how can i confirm it is working or not.. Is there a way, or an option, to open a small window and see the value of the spacemouse changing ?
 I did try with the spacenavigator and i did put the package:  install spacenavd   But i can't tell if it's working or not.

thanks

**Comment by dewiweb** [comment]
Hello,
I add additional  instructions(udev rules) to use it on Linux in the readme.md .
You can then monitor OSC output by sending OSC to a local app like [https://benjamin.kuperberg.fr/chataigne/en](https://benjamin.kuperberg.fr/chataigne/en).

**Comment by dewiweb** [comment]
Maybe you'll have to add logitech rules. Here is a good example :
[resources/udev/90-3dconnexion.rules](https://github.com/prusa3d/PrusaSlicer/blob/master/resources/udev/90-3dconnexion.rules)
It's possible yaw/pitch/roll values aren't coded in the same way on all 3dconnexion devices.
I've just got only one model to test.

**Comment by docop** [comment]
Yeah, as posted, the correct id is added too in the udev rules from before. But if i simply open Blender, i can 3d ordit without problem. Perhaps something  is about the rXrYrZ  for the rotate function, as the XYZ Translate do work fine. Or you did limit the reading to 7 byte for the group action vs 13 for total.. What version do you have?
 I could try out later over a single small unit SpaceNavigator maybe..

**Comment by dewiweb** [comment]
I've got a space mouse compact model.

**Comment by docop** [comment]
I found a soft that can show all the live data of the unit and button activation:
https://github.com/todbot/hidapitester
 ex pr the SpacePilot:
./hidapitester --vidpid 046D:C625 -l 64 -t 1500 --open --read-input-forever

 And here is the full dump of the spacemouse wireless (while connected wired over USB)  that i did found.
https://pastebin.com/GD5mEKW6

 hope this can help. i don't know how to do a dump, but if you let me know how, i could from the unit i have.

**Comment by LuftGstell** [comment]
Hi,thanks for this app. Just one question.
What is the resolution the App uses to translate mouse motion into OSC messages (7bit, 14bit....) Thanks

**Comment by dewiweb** [comment]
@LuftGstell Don't know what you're talking about. Do you want to talk about OSC send rate?

**Comment by LuftGstell** [comment]
Hi thanks for getting back to me!When you tap into the data coming from the 3d mouse and convert it into OSC data, what is the resolution of this data being passed on to (in my case cubase) the host?Is it better that 7bit midi 1.0 provides me currently?Thank you


Sent from Yahoo Mail for iPhone


On Wednesday, January 24, 2024, 10:57, dewiweb ***@***.***> wrote:




@LuftGstell Don't know what you're talking about. Do you want to talk about OSC send rate?

**Comment by dewiweb** [comment]
It convert all hid incoming datas from space mouse in OSC messages, so resolution is the one provided natively by the hardware.

**Comment by LuftGstell** [comment]
Thank you so much!


Sent from Yahoo Mail for iPhone


On Thursday, January 25, 2024, 14:18, dewiweb ***@***.***> wrote:




It convert all hid incoming datas from space mouse in OSC messages, so resolution is the one provided natively by the hardware.
