### ISSUE TITLE
compatible with Space Mouse Pro?

### ISSUE THREAD

**Issue by zebra1993** [dewiweb/spacemouse-osc#5]
Good Day

Ive bought a Spacemouse Pro ages ago.
in search to get data into another programm ive found your tool.
Right now im struggling with resceiving OSC from your tool though.
have changed the 'Remote OSC Server' to my IP (normal and 127.0.0.1), port 4003.
i don't see any messages in Protokol nor Chataigne.
I am wiggling the knob on the mouse around, no messages.

Any suggestion what i am missing?

My configuration currently:
![image](https://github.com/dewiweb/spacemouse-osc/assets/3521804/98d7fa82-7466-4ecf-9607-3d9e91b7713c)
![image](https://github.com/dewiweb/spacemouse-osc/assets/3521804/503e39d4-6229-481a-be87-e5a19e7cd915)

**Comment by dewiweb** [comment]
Hello,
Which version did you use (on which OS)?
Did you create udev rules if you ran it on a linux OS?

**Comment by zebra1993** [comment]
Good Morning
I'm on Windows 10, 
With Mouse3D-OSC version 1.0.7 (the newest in the repo releases)

Ive tried to change the startup order (your tool first then chataigne or the other way round)
Not via a USB hub, with USB hub, no change

**Comment by dewiweb** [comment]
I just published a pre-release : [https://github.com/dewiweb/spacemouse-osc/releases/tag/v2.0.0-alpha.4](https://github.com/dewiweb/spacemouse-osc/releases/tag/v2.0.0-alpha.4)
I'm not able to test it yet. Maybe I'll can investigate about this tomorrow. Is your spacemouse pro wireless or wired model?

**Comment by zebra1993** [comment]
I do have a wired Spacemouse Pro.
Tried your V2.00.A4 a quick test, no change. is there a way i can check if the spacemouse itself is sending the correct data?
Ive tried the viewer of the 3dConnexion software and it works there but is there a way to check if your programm is receiving the USB data?

**Comment by dewiweb** [comment]
Maybe you can try to launch it with cmd(don't know if it return logs), or if you've got developper skill, you can clone the repo and launch ```yarn``` command then ```yarn start```

**Comment by dewiweb** [comment]
Can you send me Vendor ID and Product ID ?
_On Windows: Assuming your device is connected to the computer, go to "Device manager", find your device, right click on it, select "Properties", go to "Details" tab, select "Hardware IDs" from the drop-down, and you will find an entry of a form:

HID\VID_046D&PID_C05A 

which are correspondingly vendor and product IDs._

**Comment by zebra1993** [comment]
Didnt find the mouse in hardware manager, took a screenshot with Device tree viewer instead.
hope it helps.
i did get the project into VSCode, didnt have time to look at it yet. 
![image](https://github.com/dewiweb/spacemouse-osc/assets/3521804/1081b6eb-f34b-4269-aecb-f20ea2b83fde)

**Comment by zebra1993** [comment]
I think ive found the issue, will make a PR when i'm done with getting the buttons to report their status as well. (want to try to get them working aswell)

**Comment by zebra1993** [comment]
youve seen the pullrequest, awesome. 
just a quick question, how do i build my own branch as an exe to not have to keep VScode open?

**Comment by dewiweb** [comment]
I published a new pre-release including your pr just now.

**Comment by dewiweb** [comment]
I published a pre-release including your pr just now.

**Comment by dewiweb** [comment]
@zebra1993  I made some improvements in latest release([V2.2.2](https://github.com/dewiweb/spacemouse-osc/releases/tag/v2.2.2)), if you're interested to test it, user feedbacks are always welcome...
